// GENERATED by scripts/fetch-vehicle-images.mjs — do not edit by hand.
// CC-licensed vehicle photos from Wikimedia Commons (self-hosted under apps/web/public/vehicles).
import type { VehicleImageCredit } from '../types'

export const VEHICLE_IMAGES: Record<string, { imageUrl: string, imageCredit: VehicleImageCredit }> = {
  "clio-essence": {
    "imageUrl": "/vehicles/clio-essence.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Renault_Clio_V_Genf_2019_1Y7A5590.jpg"
    }
  },
  "clio-diesel": {
    "imageUrl": "/vehicles/clio-diesel.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Renault_Clio_V_Genf_2019_1Y7A5590.jpg"
    }
  },
  "zoe-electric": {
    "imageUrl": "/vehicles/zoe-electric.jpg",
    "imageCredit": {
      "author": "werner hillebrand-hansen",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Renault_Zoe_charging.jpg"
    }
  },
  "e208-electric": {
    "imageUrl": "/vehicles/e208-electric.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2020_Peugeot_208_GT_Line_PureTech_1.2_Front.jpg"
    }
  },
  "208-essence": {
    "imageUrl": "/vehicles/208-essence.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2020_Peugeot_208_GT_Line_PureTech_1.2_Front.jpg"
    }
  },
  "yaris-hybrid": {
    "imageUrl": "/vehicles/yaris-hybrid.jpg",
    "imageCredit": {
      "author": "Alexander-93",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2024_Toyota_Yaris_Hybrid_130_(XP210)_IMG_9910.jpg"
    }
  },
  "megane-estate-essence": {
    "imageUrl": "/vehicles/megane-estate-essence.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2017_Renault_Megane_Dynamique_S_NAV_DC_1.5_Front.jpg"
    }
  },
  "passat-sw-diesel": {
    "imageUrl": "/vehicles/passat-sw-diesel.jpg",
    "imageCredit": {
      "author": "Herranderssvensson",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Volkswagen_Passat_B8_fr.jpg"
    }
  },
  "3008-hybrid": {
    "imageUrl": "/vehicles/3008-hybrid.jpg",
    "imageCredit": {
      "author": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peugeot_3008_THP_165_EAT6_Allure_GT-Line_(II)_%E2%80%93_Frontansicht_(1)%2C_20._September_2017%2C_D%C3%BCsseldorf.jpg"
    }
  },
  "3008-phev": {
    "imageUrl": "/vehicles/3008-phev.jpg",
    "imageCredit": {
      "author": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peugeot_3008_THP_165_EAT6_Allure_GT-Line_(II)_%E2%80%93_Frontansicht_(1)%2C_20._September_2017%2C_D%C3%BCsseldorf.jpg"
    }
  },
  "model3-electric": {
    "imageUrl": "/vehicles/model3-electric.jpg",
    "imageCredit": {
      "author": "Alexander-93",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tesla_Model_3_(2023)_Autofr%C3%BChling_Ulm_IMG_9282.jpg"
    }
  },
  "modely-electric": {
    "imageUrl": "/vehicles/modely-electric.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tesla_Model_Y_(2025)_MYLE_Festival_2025_DSC_9565.jpg"
    }
  },
  "id4-electric": {
    "imageUrl": "/vehicles/id4-electric.jpg",
    "imageCredit": {
      "author": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:VW_ID.4_1st_%E2%80%93_f_26122020.jpg"
    }
  },
  "berlingo-essence": {
    "imageUrl": "/vehicles/berlingo-essence.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2018_Peugeot_Rifter_Allure_BlueHDi_1.6_Front.jpg"
    }
  },
  "eberlingo-electric": {
    "imageUrl": "/vehicles/eberlingo-electric.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2018_Peugeot_Rifter_Allure_BlueHDi_1.6_Front.jpg"
    }
  },
  "sandero-essence": {
    "imageUrl": "/vehicles/sandero-essence.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dacia_Sandero_Stepway_III_IMG_4214.jpg"
    }
  },
  "c3-essence": {
    "imageUrl": "/vehicles/c3-essence.jpg",
    "imageCredit": {
      "author": "El monty",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Citro%C3%ABn_C3_-_2016_(17).jpg"
    }
  },
  "polo-essence": {
    "imageUrl": "/vehicles/polo-essence.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2018_Volkswagen_Polo_SE_1.0_Front.jpg"
    }
  },
  "308-essence": {
    "imageUrl": "/vehicles/308-essence.jpg",
    "imageCredit": {
      "author": "A.BourgeoisP",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2022_-_Peugeot_308_III_(C)_-_196.jpg"
    }
  },
  "308-hybrid": {
    "imageUrl": "/vehicles/308-hybrid.jpg",
    "imageCredit": {
      "author": "A.BourgeoisP",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2022_-_Peugeot_308_III_(C)_-_196.jpg"
    }
  },
  "e308-electric": {
    "imageUrl": "/vehicles/e308-electric.jpg",
    "imageCredit": {
      "author": "A.BourgeoisP",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2022_-_Peugeot_308_III_(C)_-_196.jpg"
    }
  },
  "megane-etech-electric": {
    "imageUrl": "/vehicles/megane-etech-electric.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Renault_Megane_E-Tech_IAA_2021_1X7A0209.jpg"
    }
  },
  "golf-essence": {
    "imageUrl": "/vehicles/golf-essence.jpg",
    "imageCredit": {
      "author": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:2020_Volkswagen_Golf_Style_TDi_S-A_2.0.jpg"
    }
  },
  "captur-essence": {
    "imageUrl": "/vehicles/captur-essence.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Renault_Captur_II_at_IAA_2019_IMG_0446.jpg"
    }
  },
  "captur-etech-hybrid": {
    "imageUrl": "/vehicles/captur-etech-hybrid.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Renault_Captur_II_at_IAA_2019_IMG_0446.jpg"
    }
  },
  "2008-essence": {
    "imageUrl": "/vehicles/2008-essence.jpg",
    "imageCredit": {
      "author": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peugeot_2008_B_Retro_Classics_2020_IMG_0025.jpg"
    }
  }
}
