import type { Vehicle } from '../types'

export const VEHICLE_PRESETS: readonly Vehicle[] = [
  {
    id: 'clio-essence',
    label: 'Renault Clio TCe 90 essence',
    brand: 'Renault',
    searchModel: 'Clio',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 19500,
    consumption: 5.8,
    co2: 134,
    insuranceCategory: 11,
    maintenanceAnnual: 380,
    tireLifeKm: 40000,
    tireSetPrice: 480,
    malus: 0,
    bonus: 0,
    curbWeight: 1180,
    releaseYear: 2024,
  },
  {
    id: 'clio-diesel',
    label: 'Renault Clio Blue dCi 100 diesel',
    brand: 'Renault',
    searchModel: 'Clio',
    category: 'cityCar',
    energy: 'diesel',
    purchasePrice: 22300,
    consumption: 4.1,
    co2: 108,
    insuranceCategory: 11,
    maintenanceAnnual: 460,
    tireLifeKm: 42000,
    tireSetPrice: 500,
    malus: 0,
    bonus: 0,
    curbWeight: 1240,
    releaseYear: 2024,
  },
  {
    id: 'zoe-electric',
    label: 'Renault Zoé R135 électrique',
    brand: 'Renault',
    searchModel: 'Zoé',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 35100,
    consumption: 17.2,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 180,
    tireLifeKm: 38000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 4000,
    curbWeight: 1577,
    releaseYear: 2024,
    wltpRangeKm: 395,
  },
  {
    id: 'e208-electric',
    label: 'Peugeot e-208 GT 156ch',
    brand: 'Peugeot',
    searchModel: '208',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 37800,
    consumption: 15.8,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 200,
    tireLifeKm: 38000,
    tireSetPrice: 540,
    malus: 0,
    bonus: 4000,
    curbWeight: 1455,
    releaseYear: 2024,
    wltpRangeKm: 400,
  },
  {
    id: 'mg4-electric',
    label: 'MG4 Standard 64kWh',
    brand: 'MG',
    searchModel: 'MG4',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 30990,
    consumption: 16.5,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 220,
    tireLifeKm: 36000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 4000,
    curbWeight: 1655,
    releaseYear: 2024,
    wltpRangeKm: 450,
  },
  {
    id: 'yaris-hybrid',
    label: 'Toyota Yaris Hybride 116h',
    brand: 'Toyota',
    searchModel: 'Yaris',
    category: 'cityCar',
    energy: 'hybrid',
    purchasePrice: 24900,
    consumption: 3.8,
    co2: 87,
    insuranceCategory: 12,
    maintenanceAnnual: 340,
    tireLifeKm: 45000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 0,
    curbWeight: 1145,
    releaseYear: 2024,
  },
  {
    id: 'megane-estate-essence',
    label: 'Renault Mégane Estate TCe 140 essence',
    brand: 'Renault',
    searchModel: 'Mégane Estate',
    category: 'estate',
    energy: 'gasoline',
    purchasePrice: 27500,
    consumption: 6.4,
    co2: 145,
    insuranceCategory: 13,
    maintenanceAnnual: 460,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 270,
    bonus: 0,
    curbWeight: 1310,
    releaseYear: 2023,
  },
  {
    id: 'passat-sw-diesel',
    label: 'Volkswagen Passat SW 2.0 TDI 150 DSG',
    brand: 'Volkswagen',
    searchModel: 'Passat SW',
    category: 'estate',
    energy: 'diesel',
    purchasePrice: 42500,
    consumption: 5.2,
    co2: 137,
    insuranceCategory: 16,
    maintenanceAnnual: 720,
    tireLifeKm: 45000,
    tireSetPrice: 720,
    malus: 0,
    bonus: 0,
    curbWeight: 1640,
    releaseYear: 2024,
  },
  {
    id: '3008-hybrid',
    label: 'Peugeot 3008 Hybrid 136 e-DCS6',
    brand: 'Peugeot',
    searchModel: '3008',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 37500,
    consumption: 5.6,
    co2: 127,
    insuranceCategory: 15,
    maintenanceAnnual: 560,
    tireLifeKm: 42000,
    tireSetPrice: 680,
    malus: 60,
    bonus: 0,
    curbWeight: 1505,
    releaseYear: 2024,
  },
  {
    id: '3008-phev',
    label: 'Peugeot 3008 Hybrid Plug-in 195',
    brand: 'Peugeot',
    searchModel: '3008',
    category: 'suv',
    energy: 'phev',
    purchasePrice: 47900,
    consumption: 7.4,
    co2: 32,
    insuranceCategory: 17,
    maintenanceAnnual: 620,
    tireLifeKm: 38000,
    tireSetPrice: 720,
    malus: 0,
    bonus: 0,
    curbWeight: 1815,
    releaseYear: 2024,
    wltpRangeKm: 65,
  },
  {
    id: 'model3-electric',
    label: 'Tesla Model 3 Propulsion',
    brand: 'Tesla',
    searchModel: 'Model 3',
    category: 'sedan',
    energy: 'electric',
    purchasePrice: 42990,
    consumption: 14.4,
    co2: 0,
    insuranceCategory: 18,
    maintenanceAnnual: 240,
    tireLifeKm: 35000,
    tireSetPrice: 760,
    malus: 0,
    bonus: 0,
    curbWeight: 1765,
    releaseYear: 2024,
    wltpRangeKm: 513,
  },
  {
    id: 'modely-electric',
    label: 'Tesla Model Y Propulsion',
    brand: 'Tesla',
    searchModel: 'Model Y',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 44990,
    consumption: 15.8,
    co2: 0,
    insuranceCategory: 18,
    maintenanceAnnual: 260,
    tireLifeKm: 35000,
    tireSetPrice: 820,
    malus: 0,
    bonus: 0,
    curbWeight: 1909,
    releaseYear: 2024,
    wltpRangeKm: 455,
  },
  {
    id: 'id4-electric',
    label: 'Volkswagen ID.4 Pro 286ch',
    brand: 'Volkswagen',
    searchModel: 'ID.4',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 49600,
    consumption: 16.9,
    co2: 0,
    insuranceCategory: 17,
    maintenanceAnnual: 280,
    tireLifeKm: 36000,
    tireSetPrice: 820,
    malus: 0,
    bonus: 0,
    curbWeight: 2125,
    releaseYear: 2024,
    wltpRangeKm: 524,
  },
  {
    id: 'tiguan-essence',
    label: 'Volkswagen Tiguan 1.5 eTSI 150ch',
    brand: 'Volkswagen',
    searchModel: 'Tiguan',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 41900,
    consumption: 6.8,
    co2: 154,
    insuranceCategory: 16,
    maintenanceAnnual: 620,
    tireLifeKm: 40000,
    tireSetPrice: 740,
    malus: 740,
    bonus: 0,
    curbWeight: 1565,
    releaseYear: 2024,
  },
  {
    id: 'berlingo-essence',
    label: 'Citroën Berlingo PureTech 130',
    brand: 'Citroën',
    searchModel: 'Berlingo',
    category: 'utility',
    energy: 'gasoline',
    purchasePrice: 30500,
    consumption: 6.9,
    co2: 156,
    insuranceCategory: 13,
    maintenanceAnnual: 480,
    tireLifeKm: 45000,
    tireSetPrice: 560,
    malus: 740,
    bonus: 0,
    curbWeight: 1430,
    releaseYear: 2024,
  },
  {
    id: 'eberlingo-electric',
    label: 'Citroën ë-Berlingo électrique',
    brand: 'Citroën',
    searchModel: 'Berlingo',
    category: 'utility',
    energy: 'electric',
    purchasePrice: 39400,
    consumption: 19.8,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1742,
    releaseYear: 2024,
    wltpRangeKm: 270,
  },
  // --- Top-sellers ajoutés (marché France 2023-2024) ---
  {
    id: '208-essence',
    label: 'Peugeot 208 PureTech 100',
    brand: 'Peugeot',
    searchModel: '208',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 20300,
    consumption: 5.5,
    co2: 124,
    insuranceCategory: 11,
    maintenanceAnnual: 380,
    tireLifeKm: 40000,
    tireSetPrice: 480,
    malus: 0,
    bonus: 0,
    curbWeight: 1075,
    releaseYear: 2024,
  },
  {
    id: 'sandero-essence',
    label: 'Dacia Sandero TCe 90',
    brand: 'Dacia',
    searchModel: 'Sandero',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 14400,
    consumption: 5.7,
    co2: 130,
    insuranceCategory: 10,
    maintenanceAnnual: 320,
    tireLifeKm: 42000,
    tireSetPrice: 420,
    malus: 0,
    bonus: 0,
    curbWeight: 1180,
    releaseYear: 2024,
  },
  {
    id: 'c3-essence',
    label: 'Citroën C3 PureTech 83',
    brand: 'Citroën',
    searchModel: 'C3',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 16500,
    consumption: 5.6,
    co2: 128,
    insuranceCategory: 10,
    maintenanceAnnual: 360,
    tireLifeKm: 40000,
    tireSetPrice: 440,
    malus: 0,
    bonus: 0,
    curbWeight: 1090,
    releaseYear: 2024,
  },
  {
    id: 'fiat500-hybrid',
    label: 'Fiat 500 Hybrid 70',
    brand: 'Fiat',
    searchModel: '500',
    category: 'cityCar',
    energy: 'hybrid',
    purchasePrice: 16900,
    consumption: 4.6,
    co2: 105,
    insuranceCategory: 11,
    maintenanceAnnual: 360,
    tireLifeKm: 38000,
    tireSetPrice: 460,
    malus: 0,
    bonus: 0,
    curbWeight: 980,
    releaseYear: 2024,
  },
  {
    id: 'fiat500e-electric',
    label: 'Fiat 500e électrique 42 kWh',
    brand: 'Fiat',
    searchModel: '500',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 30400,
    consumption: 14.6,
    co2: 0,
    insuranceCategory: 12,
    maintenanceAnnual: 180,
    tireLifeKm: 36000,
    tireSetPrice: 500,
    malus: 0,
    bonus: 4000,
    curbWeight: 1290,
    releaseYear: 2024,
    wltpRangeKm: 320,
  },
  {
    id: 'polo-essence',
    label: 'Volkswagen Polo 1.0 TSI 95',
    brand: 'Volkswagen',
    searchModel: 'Polo',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 22300,
    consumption: 5.6,
    co2: 128,
    insuranceCategory: 12,
    maintenanceAnnual: 420,
    tireLifeKm: 42000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 0,
    curbWeight: 1190,
    releaseYear: 2024,
  },
  // Compactes
  {
    id: '308-essence',
    label: 'Peugeot 308 PureTech 130',
    brand: 'Peugeot',
    searchModel: '308',
    category: 'compact',
    energy: 'gasoline',
    purchasePrice: 30900,
    consumption: 6.0,
    co2: 134,
    insuranceCategory: 13,
    maintenanceAnnual: 460,
    tireLifeKm: 42000,
    tireSetPrice: 560,
    malus: 60,
    bonus: 0,
    curbWeight: 1320,
    releaseYear: 2024,
  },
  {
    id: '308-hybrid',
    label: 'Peugeot 308 Hybrid 136',
    brand: 'Peugeot',
    searchModel: '308',
    category: 'compact',
    energy: 'hybrid',
    purchasePrice: 34900,
    consumption: 4.8,
    co2: 109,
    insuranceCategory: 13,
    maintenanceAnnual: 480,
    tireLifeKm: 40000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1395,
    releaseYear: 2024,
  },
  {
    id: 'e308-electric',
    label: 'Peugeot e-308 électrique',
    brand: 'Peugeot',
    searchModel: '308',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 43900,
    consumption: 15.5,
    co2: 0,
    insuranceCategory: 16,
    maintenanceAnnual: 240,
    tireLifeKm: 38000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 4000,
    curbWeight: 1660,
    releaseYear: 2024,
    wltpRangeKm: 410,
  },
  {
    id: 'megane-etech-electric',
    label: 'Renault Mégane E-Tech EV60',
    brand: 'Renault',
    searchModel: 'Mégane E-Tech',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 38400,
    consumption: 16.1,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 230,
    tireLifeKm: 38000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 4000,
    curbWeight: 1636,
    releaseYear: 2024,
    wltpRangeKm: 470,
  },
  {
    id: 'golf-essence',
    label: 'Volkswagen Golf 1.5 eTSI 150',
    brand: 'Volkswagen',
    searchModel: 'Golf',
    category: 'compact',
    energy: 'gasoline',
    purchasePrice: 33500,
    consumption: 6.0,
    co2: 136,
    insuranceCategory: 14,
    maintenanceAnnual: 580,
    tireLifeKm: 42000,
    tireSetPrice: 620,
    malus: 170,
    bonus: 0,
    curbWeight: 1310,
    releaseYear: 2024,
  },
  // SUV compacts (top des ventes France)
  {
    id: 'captur-essence',
    label: 'Renault Captur TCe 140',
    brand: 'Renault',
    searchModel: 'Captur',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 26500,
    consumption: 6.1,
    co2: 138,
    insuranceCategory: 13,
    maintenanceAnnual: 450,
    tireLifeKm: 40000,
    tireSetPrice: 560,
    malus: 170,
    bonus: 0,
    curbWeight: 1335,
    releaseYear: 2024,
  },
  {
    id: 'captur-etech-hybrid',
    label: 'Renault Captur E-Tech full hybrid 145',
    brand: 'Renault',
    searchModel: 'Captur',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 30200,
    consumption: 4.7,
    co2: 105,
    insuranceCategory: 13,
    maintenanceAnnual: 430,
    tireLifeKm: 40000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1497,
    releaseYear: 2024,
  },
  {
    id: '2008-essence',
    label: 'Peugeot 2008 PureTech 130',
    brand: 'Peugeot',
    searchModel: '2008',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 27500,
    consumption: 6.0,
    co2: 136,
    insuranceCategory: 13,
    maintenanceAnnual: 450,
    tireLifeKm: 40000,
    tireSetPrice: 580,
    malus: 170,
    bonus: 0,
    curbWeight: 1267,
    releaseYear: 2024,
  },
  {
    id: 'e2008-electric',
    label: 'Peugeot e-2008 électrique 156ch',
    brand: 'Peugeot',
    searchModel: '2008',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 38400,
    consumption: 16.5,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 220,
    tireLifeKm: 38000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 4000,
    curbWeight: 1565,
    releaseYear: 2024,
    wltpRangeKm: 406,
  },
  {
    id: 'duster-essence',
    label: 'Dacia Duster TCe 130',
    brand: 'Dacia',
    searchModel: 'Duster',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 22500,
    consumption: 6.4,
    co2: 145,
    insuranceCategory: 12,
    maintenanceAnnual: 380,
    tireLifeKm: 42000,
    tireSetPrice: 540,
    malus: 270,
    bonus: 0,
    curbWeight: 1325,
    releaseYear: 2024,
  },
  {
    id: 'yariscross-hybrid',
    label: 'Toyota Yaris Cross Hybride 116h',
    brand: 'Toyota',
    searchModel: 'Yaris Cross',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 28500,
    consumption: 4.5,
    co2: 102,
    insuranceCategory: 13,
    maintenanceAnnual: 360,
    tireLifeKm: 42000,
    tireSetPrice: 540,
    malus: 0,
    bonus: 0,
    curbWeight: 1180,
    releaseYear: 2024,
  },
  {
    id: 'kona-electric',
    label: 'Hyundai Kona Electric 65 kWh',
    brand: 'Hyundai',
    searchModel: 'Kona',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 41900,
    consumption: 15.5,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 220,
    tireLifeKm: 38000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 4000,
    curbWeight: 1685,
    releaseYear: 2024,
    wltpRangeKm: 514,
  },
  // SUV moyens & berlines compactes
  {
    id: 'austral-etech-hybrid',
    label: 'Renault Austral E-Tech full hybrid 200',
    brand: 'Renault',
    searchModel: 'Austral',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 38500,
    consumption: 4.6,
    co2: 105,
    insuranceCategory: 15,
    maintenanceAnnual: 540,
    tireLifeKm: 42000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 0,
    curbWeight: 1500,
    releaseYear: 2024,
  },
  {
    id: 'tucson-hybrid',
    label: 'Hyundai Tucson Hybrid 230',
    brand: 'Hyundai',
    searchModel: 'Tucson',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 37900,
    consumption: 5.6,
    co2: 127,
    insuranceCategory: 15,
    maintenanceAnnual: 480,
    tireLifeKm: 42000,
    tireSetPrice: 680,
    malus: 60,
    bonus: 0,
    curbWeight: 1500,
    releaseYear: 2024,
  },
  // Break (alternative familiale aux SUV)
  {
    id: 'octavia-essence',
    label: 'Skoda Octavia Combi 1.5 TSI 150',
    brand: 'Skoda',
    searchModel: 'Octavia Combi',
    category: 'estate',
    energy: 'gasoline',
    purchasePrice: 32900,
    consumption: 6.0,
    co2: 136,
    insuranceCategory: 14,
    maintenanceAnnual: 540,
    tireLifeKm: 42000,
    tireSetPrice: 620,
    malus: 170,
    bonus: 0,
    curbWeight: 1418,
    releaseYear: 2024,
  },
  {
    id: 'octavia-diesel',
    label: 'Skoda Octavia Combi 2.0 TDI 150',
    brand: 'Skoda',
    searchModel: 'Octavia Combi',
    category: 'estate',
    energy: 'diesel',
    purchasePrice: 35400,
    consumption: 5.0,
    co2: 132,
    insuranceCategory: 14,
    maintenanceAnnual: 620,
    tireLifeKm: 45000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 0,
    curbWeight: 1495,
    releaseYear: 2024,
  },
  // Utilitaires familiaux
  {
    id: 'rifter-essence',
    label: 'Peugeot Rifter PureTech 130',
    brand: 'Peugeot',
    searchModel: 'Rifter',
    category: 'utility',
    energy: 'gasoline',
    purchasePrice: 30900,
    consumption: 6.9,
    co2: 156,
    insuranceCategory: 13,
    maintenanceAnnual: 480,
    tireLifeKm: 45000,
    tireSetPrice: 560,
    malus: 740,
    bonus: 0,
    curbWeight: 1430,
    releaseYear: 2024,
  },
  // --- Pack électrique élargi (top ventes EV France 2024-2026) ---
  {
    id: 'spring-electric',
    label: 'Dacia Spring 65 électrique',
    brand: 'Dacia',
    searchModel: 'Spring',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 17900,
    consumption: 13.9,
    co2: 0,
    insuranceCategory: 10,
    maintenanceAnnual: 160,
    tireLifeKm: 38000,
    tireSetPrice: 320,
    malus: 0,
    bonus: 4000,
    curbWeight: 1006,
    releaseYear: 2024,
    wltpRangeKm: 220,
  },
  {
    id: 'r5-etech-electric',
    label: 'Renault 5 E-Tech 150 52kWh',
    brand: 'Renault',
    searchModel: '5 E-Tech',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 27900,
    consumption: 14.7,
    co2: 0,
    insuranceCategory: 12,
    maintenanceAnnual: 200,
    tireLifeKm: 36000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 4000,
    curbWeight: 1449,
    releaseYear: 2025,
    wltpRangeKm: 410,
  },
  {
    id: 'ec3-electric',
    label: 'Citroën ë-C3 You 44kWh',
    brand: 'Citroën',
    searchModel: 'C3',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 23300,
    consumption: 16.3,
    co2: 0,
    insuranceCategory: 11,
    maintenanceAnnual: 200,
    tireLifeKm: 38000,
    tireSetPrice: 460,
    malus: 0,
    bonus: 4000,
    curbWeight: 1408,
    releaseYear: 2024,
    wltpRangeKm: 320,
  },
  {
    id: 'id3-electric',
    label: 'Volkswagen ID.3 Pro 58kWh',
    brand: 'Volkswagen',
    searchModel: 'ID.3',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 39990,
    consumption: 15.9,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 36000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 4000,
    curbWeight: 1810,
    releaseYear: 2024,
    wltpRangeKm: 426,
  },
  {
    id: 'ec4-electric',
    label: 'Citroën ë-C4 50kWh',
    brand: 'Citroën',
    searchModel: 'C4',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 35800,
    consumption: 15.6,
    co2: 0,
    insuranceCategory: 13,
    maintenanceAnnual: 240,
    tireLifeKm: 38000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1614,
    releaseYear: 2024,
    wltpRangeKm: 357,
  },
  {
    id: 'scenic-etech-electric',
    label: 'Renault Scenic E-Tech 87kWh',
    brand: 'Renault',
    searchModel: 'Scénic E-Tech',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 44000,
    consumption: 16.8,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 260,
    tireLifeKm: 38000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 4000,
    curbWeight: 1842,
    releaseYear: 2025,
    wltpRangeKm: 625,
  },
  {
    id: 'enyaq-electric',
    label: 'Skoda Enyaq 85',
    brand: 'Skoda',
    searchModel: 'Enyaq',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 48990,
    consumption: 17.0,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 280,
    tireLifeKm: 38000,
    tireSetPrice: 680,
    malus: 0,
    bonus: 0,
    curbWeight: 2128,
    releaseYear: 2024,
    wltpRangeKm: 580,
  },
  {
    id: 'ioniq5-electric',
    label: 'Hyundai Ioniq 5 77kWh',
    brand: 'Hyundai',
    searchModel: 'Ioniq 5',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 49900,
    consumption: 17.7,
    co2: 0,
    insuranceCategory: 16,
    maintenanceAnnual: 280,
    tireLifeKm: 38000,
    tireSetPrice: 720,
    malus: 0,
    bonus: 0,
    curbWeight: 2010,
    releaseYear: 2024,
    wltpRangeKm: 507,
  },
  {
    id: 'ev6-electric',
    label: 'Kia EV6 77kWh',
    brand: 'Kia',
    searchModel: 'EV6',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 50990,
    consumption: 17.2,
    co2: 0,
    insuranceCategory: 16,
    maintenanceAnnual: 280,
    tireLifeKm: 38000,
    tireSetPrice: 720,
    malus: 0,
    bonus: 0,
    curbWeight: 2010,
    releaseYear: 2024,
    wltpRangeKm: 528,
  },
  {
    id: 'byd-atto3',
    label: 'BYD Atto 3 60kWh',
    brand: 'BYD',
    searchModel: 'Atto 3',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 38000,
    consumption: 16.0,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 250,
    tireLifeKm: 38000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 4000,
    curbWeight: 1750,
    releaseYear: 2024,
    wltpRangeKm: 420,
  },
  {
    id: 'mgzs-electric',
    label: 'MG ZS EV Long Range 70kWh',
    brand: 'MG',
    searchModel: 'ZS EV',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 32990,
    consumption: 17.7,
    co2: 0,
    insuranceCategory: 13,
    maintenanceAnnual: 230,
    tireLifeKm: 38000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1612,
    releaseYear: 2024,
    wltpRangeKm: 440,
  },
  {
    id: 'model3-lr-electric',
    label: 'Tesla Model 3 Long Range',
    brand: 'Tesla',
    searchModel: 'Model 3',
    category: 'sedan',
    energy: 'electric',
    purchasePrice: 49990,
    consumption: 14.7,
    co2: 0,
    insuranceCategory: 18,
    maintenanceAnnual: 260,
    tireLifeKm: 35000,
    tireSetPrice: 780,
    malus: 0,
    bonus: 0,
    curbWeight: 1844,
    releaseYear: 2024,
    wltpRangeKm: 678,
  },
  {
    id: 'modely-lr-electric',
    label: 'Tesla Model Y Long Range',
    brand: 'Tesla',
    searchModel: 'Model Y',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 52990,
    consumption: 16.1,
    co2: 0,
    insuranceCategory: 18,
    maintenanceAnnual: 280,
    tireLifeKm: 35000,
    tireSetPrice: 840,
    malus: 0,
    bonus: 0,
    curbWeight: 1979,
    releaseYear: 2024,
    wltpRangeKm: 600,
  },
  {
    id: 'q4-etron',
    label: 'Audi Q4 e-tron 45',
    brand: 'Audi',
    searchModel: 'Q4 e-tron',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 52900,
    consumption: 17.0,
    co2: 0,
    insuranceCategory: 18,
    maintenanceAnnual: 320,
    tireLifeKm: 38000,
    tireSetPrice: 760,
    malus: 0,
    bonus: 0,
    curbWeight: 2110,
    releaseYear: 2024,
    wltpRangeKm: 519,
  },
  {
    id: 'bmw-i4',
    label: 'BMW i4 eDrive40',
    brand: 'BMW',
    searchModel: 'i4',
    category: 'sedan',
    energy: 'electric',
    purchasePrice: 58000,
    consumption: 15.4,
    co2: 0,
    insuranceCategory: 19,
    maintenanceAnnual: 340,
    tireLifeKm: 38000,
    tireSetPrice: 800,
    malus: 0,
    bonus: 0,
    curbWeight: 2050,
    releaseYear: 2024,
    wltpRangeKm: 590,
  },
  {
    id: 'polestar2',
    label: 'Polestar 2 Long Range Single Motor',
    brand: 'Polestar',
    searchModel: '2',
    category: 'sedan',
    energy: 'electric',
    purchasePrice: 49900,
    consumption: 15.5,
    co2: 0,
    insuranceCategory: 17,
    maintenanceAnnual: 280,
    tireLifeKm: 35000,
    tireSetPrice: 740,
    malus: 0,
    bonus: 0,
    curbWeight: 2050,
    releaseYear: 2024,
    wltpRangeKm: 654,
  },
  // --- Premium allemandes thermiques & hybrides (marché France 2024-2026) ---
  {
    id: 'mercedes-classe-a-essence',
    label: 'Mercedes Classe A 180 essence 7G-DCT',
    brand: 'Mercedes',
    searchModel: 'Classe A',
    category: 'compact',
    energy: 'gasoline',
    purchasePrice: 38500,
    consumption: 6.1,
    co2: 138,
    insuranceCategory: 16,
    maintenanceAnnual: 640,
    tireLifeKm: 40000,
    tireSetPrice: 680,
    malus: 210,
    bonus: 0,
    curbWeight: 1410,
    releaseYear: 2024,
  },
  {
    id: 'bmw-serie1-essence',
    label: 'BMW Série 1 118i essence DKG',
    brand: 'BMW',
    searchModel: 'Série 1',
    category: 'compact',
    energy: 'gasoline',
    purchasePrice: 37900,
    consumption: 6.0,
    co2: 136,
    insuranceCategory: 16,
    maintenanceAnnual: 620,
    tireLifeKm: 40000,
    tireSetPrice: 680,
    malus: 170,
    bonus: 0,
    curbWeight: 1390,
    releaseYear: 2024,
  },
  {
    id: 'bmw-serie3-essence',
    label: 'BMW Série 3 320i essence Steptronic',
    brand: 'BMW',
    searchModel: 'Série 3',
    category: 'sedan',
    energy: 'gasoline',
    purchasePrice: 49900,
    consumption: 6.4,
    co2: 145,
    insuranceCategory: 18,
    maintenanceAnnual: 760,
    tireLifeKm: 40000,
    tireSetPrice: 760,
    malus: 270,
    bonus: 0,
    curbWeight: 1545,
    releaseYear: 2024,
  },
  {
    id: 'bmw-320d-diesel',
    label: 'BMW Série 3 320d diesel Steptronic',
    brand: 'BMW',
    searchModel: 'Série 3',
    category: 'sedan',
    energy: 'diesel',
    purchasePrice: 52400,
    consumption: 4.8,
    co2: 126,
    insuranceCategory: 18,
    maintenanceAnnual: 820,
    tireLifeKm: 45000,
    tireSetPrice: 760,
    malus: 0,
    bonus: 0,
    curbWeight: 1610,
    releaseYear: 2024,
  },
  {
    id: 'bmw-serie3-touring-diesel',
    label: 'BMW Série 3 Touring 320d diesel',
    brand: 'BMW',
    searchModel: 'Série 3 Touring',
    category: 'estate',
    energy: 'diesel',
    purchasePrice: 54900,
    consumption: 5.0,
    co2: 131,
    insuranceCategory: 18,
    maintenanceAnnual: 840,
    tireLifeKm: 45000,
    tireSetPrice: 780,
    malus: 0,
    bonus: 0,
    curbWeight: 1680,
    releaseYear: 2024,
  },
  {
    id: 'mercedes-c220d-diesel',
    label: 'Mercedes Classe C 220 d diesel',
    brand: 'Mercedes',
    searchModel: 'Classe C',
    category: 'sedan',
    energy: 'diesel',
    purchasePrice: 53900,
    consumption: 4.9,
    co2: 129,
    insuranceCategory: 18,
    maintenanceAnnual: 820,
    tireLifeKm: 45000,
    tireSetPrice: 780,
    malus: 0,
    bonus: 0,
    curbWeight: 1675,
    releaseYear: 2024,
  },
  {
    id: 'audi-a3-essence',
    label: 'Audi A3 Sportback 35 TFSI essence',
    brand: 'Audi',
    searchModel: 'A3',
    category: 'compact',
    energy: 'gasoline',
    purchasePrice: 38900,
    consumption: 5.9,
    co2: 134,
    insuranceCategory: 16,
    maintenanceAnnual: 620,
    tireLifeKm: 40000,
    tireSetPrice: 680,
    malus: 170,
    bonus: 0,
    curbWeight: 1370,
    releaseYear: 2024,
  },
  {
    id: 'audi-a4-avant-diesel',
    label: 'Audi A4 Avant 35 TDI diesel S tronic',
    brand: 'Audi',
    searchModel: 'A4 Avant',
    category: 'estate',
    energy: 'diesel',
    purchasePrice: 51900,
    consumption: 5.1,
    co2: 134,
    insuranceCategory: 18,
    maintenanceAnnual: 800,
    tireLifeKm: 45000,
    tireSetPrice: 760,
    malus: 0,
    bonus: 0,
    curbWeight: 1640,
    releaseYear: 2024,
  },
  {
    id: 'audi-q3-essence',
    label: 'Audi Q3 35 TFSI essence S tronic',
    brand: 'Audi',
    searchModel: 'Q3',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 43900,
    consumption: 6.7,
    co2: 152,
    insuranceCategory: 17,
    maintenanceAnnual: 660,
    tireLifeKm: 40000,
    tireSetPrice: 720,
    malus: 540,
    bonus: 0,
    curbWeight: 1560,
    releaseYear: 2024,
  },
  // --- PHEV élargi (marché France 2024-2026) ---
  {
    id: 'captur-phev',
    label: 'Renault Captur E-Tech plug-in 160',
    brand: 'Renault',
    searchModel: 'Captur',
    category: 'suv',
    energy: 'phev',
    purchasePrice: 36500,
    consumption: 6.8,
    co2: 32,
    insuranceCategory: 14,
    maintenanceAnnual: 480,
    tireLifeKm: 38000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1564,
    releaseYear: 2024,
    wltpRangeKm: 49,
  },
  {
    id: 'rafale-phev',
    label: 'Renault Rafale E-Tech 4x4 300 plug-in',
    brand: 'Renault',
    searchModel: 'Rafale',
    category: 'suv',
    energy: 'phev',
    purchasePrice: 54000,
    consumption: 7.0,
    co2: 25,
    insuranceCategory: 17,
    maintenanceAnnual: 620,
    tireLifeKm: 38000,
    tireSetPrice: 720,
    malus: 0,
    bonus: 0,
    curbWeight: 1968,
    releaseYear: 2025,
    wltpRangeKm: 100,
  },
  {
    id: 'cupra-formentor-phev',
    label: 'Cupra Formentor VZ e-Hybrid plug-in',
    brand: 'Cupra',
    searchModel: 'Formentor',
    category: 'suv',
    energy: 'phev',
    purchasePrice: 47900,
    consumption: 7.2,
    co2: 30,
    insuranceCategory: 16,
    maintenanceAnnual: 580,
    tireLifeKm: 38000,
    tireSetPrice: 700,
    malus: 0,
    bonus: 0,
    curbWeight: 1736,
    releaseYear: 2024,
    wltpRangeKm: 100,
  },
  {
    id: 'sportage-phev',
    label: 'Kia Sportage 1.6 T-GDi plug-in hybrid',
    brand: 'Kia',
    searchModel: 'Sportage',
    category: 'suv',
    energy: 'phev',
    purchasePrice: 46900,
    consumption: 6.6,
    co2: 25,
    insuranceCategory: 16,
    maintenanceAnnual: 540,
    tireLifeKm: 40000,
    tireSetPrice: 700,
    malus: 0,
    bonus: 0,
    curbWeight: 1832,
    releaseYear: 2024,
    wltpRangeKm: 70,
  },
  {
    id: 'bmw-330e-phev',
    label: 'BMW Série 3 330e plug-in hybrid',
    brand: 'BMW',
    searchModel: 'Série 3',
    category: 'sedan',
    energy: 'phev',
    purchasePrice: 56900,
    consumption: 6.5,
    co2: 26,
    insuranceCategory: 18,
    maintenanceAnnual: 720,
    tireLifeKm: 40000,
    tireSetPrice: 780,
    malus: 0,
    bonus: 0,
    curbWeight: 1815,
    releaseYear: 2024,
    wltpRangeKm: 90,
  },
  {
    id: 'mercedes-glc300e-phev',
    label: 'Mercedes GLC 300 e plug-in hybrid',
    brand: 'Mercedes',
    searchModel: 'GLC',
    category: 'suv',
    energy: 'phev',
    purchasePrice: 68900,
    consumption: 7.0,
    co2: 18,
    insuranceCategory: 19,
    maintenanceAnnual: 820,
    tireLifeKm: 40000,
    tireSetPrice: 840,
    malus: 0,
    bonus: 0,
    curbWeight: 2185,
    releaseYear: 2024,
    wltpRangeKm: 120,
  },
  // --- Hybrides full hybrid élargis ---
  {
    id: 'corolla-hybrid',
    label: 'Toyota Corolla Hybride 140h',
    brand: 'Toyota',
    searchModel: 'Corolla',
    category: 'compact',
    energy: 'hybrid',
    purchasePrice: 31900,
    consumption: 4.4,
    co2: 100,
    insuranceCategory: 13,
    maintenanceAnnual: 380,
    tireLifeKm: 45000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 0,
    curbWeight: 1375,
    releaseYear: 2024,
  },
  {
    id: 'chr-hybrid',
    label: 'Toyota C-HR Hybride 140h',
    brand: 'Toyota',
    searchModel: 'C-HR',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 34900,
    consumption: 4.7,
    co2: 105,
    insuranceCategory: 14,
    maintenanceAnnual: 400,
    tireLifeKm: 42000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1430,
    releaseYear: 2024,
  },
  {
    id: 'rav4-hybrid',
    label: 'Toyota RAV4 Hybride 218h',
    brand: 'Toyota',
    searchModel: 'RAV4',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 42900,
    consumption: 5.6,
    co2: 126,
    insuranceCategory: 15,
    maintenanceAnnual: 460,
    tireLifeKm: 45000,
    tireSetPrice: 700,
    malus: 60,
    bonus: 0,
    curbWeight: 1690,
    releaseYear: 2024,
  },
  {
    id: 'clio-etech-hybrid',
    label: 'Renault Clio E-Tech full hybrid 145',
    brand: 'Renault',
    searchModel: 'Clio',
    category: 'cityCar',
    energy: 'hybrid',
    purchasePrice: 25500,
    consumption: 4.2,
    co2: 95,
    insuranceCategory: 12,
    maintenanceAnnual: 400,
    tireLifeKm: 42000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 0,
    curbWeight: 1278,
    releaseYear: 2024,
  },
  {
    id: 'jazz-hybrid',
    label: 'Honda Jazz e:HEV 122',
    brand: 'Honda',
    searchModel: 'Jazz',
    category: 'cityCar',
    energy: 'hybrid',
    purchasePrice: 27900,
    consumption: 4.5,
    co2: 102,
    insuranceCategory: 12,
    maintenanceAnnual: 400,
    tireLifeKm: 42000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 0,
    curbWeight: 1322,
    releaseYear: 2024,
  },
  {
    id: 'hrv-hybrid',
    label: 'Honda HR-V e:HEV 131',
    brand: 'Honda',
    searchModel: 'HR-V',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 34900,
    consumption: 5.4,
    co2: 122,
    insuranceCategory: 14,
    maintenanceAnnual: 440,
    tireLifeKm: 42000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1380,
    releaseYear: 2024,
  },
  {
    id: 'qashqai-epower-hybrid',
    label: 'Nissan Qashqai e-Power 190',
    brand: 'Nissan',
    searchModel: 'Qashqai',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 38900,
    consumption: 5.3,
    co2: 119,
    insuranceCategory: 15,
    maintenanceAnnual: 460,
    tireLifeKm: 42000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 0,
    curbWeight: 1700,
    releaseYear: 2024,
  },
  {
    id: 'duster-hybrid',
    label: 'Dacia Duster Hybrid 140',
    brand: 'Dacia',
    searchModel: 'Duster',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 28500,
    consumption: 5.0,
    co2: 113,
    insuranceCategory: 12,
    maintenanceAnnual: 400,
    tireLifeKm: 42000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 0,
    curbWeight: 1410,
    releaseYear: 2024,
  },
  {
    id: 'jogger-hybrid',
    label: 'Dacia Jogger Hybrid 140',
    brand: 'Dacia',
    searchModel: 'Jogger',
    category: 'utility',
    energy: 'hybrid',
    purchasePrice: 25900,
    consumption: 4.9,
    co2: 112,
    insuranceCategory: 12,
    maintenanceAnnual: 400,
    tireLifeKm: 45000,
    tireSetPrice: 540,
    malus: 0,
    bonus: 0,
    curbWeight: 1407,
    releaseYear: 2024,
  },
  // --- Diesel & familiales budget ---
  {
    id: 'jogger-essence',
    label: 'Dacia Jogger TCe 110',
    brand: 'Dacia',
    searchModel: 'Jogger',
    category: 'utility',
    energy: 'gasoline',
    purchasePrice: 19900,
    consumption: 6.0,
    co2: 137,
    insuranceCategory: 11,
    maintenanceAnnual: 360,
    tireLifeKm: 45000,
    tireSetPrice: 480,
    malus: 170,
    bonus: 0,
    curbWeight: 1216,
    releaseYear: 2024,
  },
  {
    id: '3008-diesel',
    label: 'Peugeot 3008 BlueHDi 130 diesel',
    brand: 'Peugeot',
    searchModel: '3008',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 39900,
    consumption: 5.0,
    co2: 132,
    insuranceCategory: 15,
    maintenanceAnnual: 620,
    tireLifeKm: 45000,
    tireSetPrice: 680,
    malus: 0,
    bonus: 0,
    curbWeight: 1530,
    releaseYear: 2024,
  },
  {
    id: '308-diesel',
    label: 'Peugeot 308 BlueHDi 130 diesel',
    brand: 'Peugeot',
    searchModel: '308',
    category: 'compact',
    energy: 'diesel',
    purchasePrice: 33500,
    consumption: 4.6,
    co2: 121,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1380,
    releaseYear: 2024,
  },
  {
    id: 'kuga-diesel',
    label: 'Ford Kuga EcoBlue 150 diesel',
    brand: 'Ford',
    searchModel: 'Kuga',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 38500,
    consumption: 5.4,
    co2: 142,
    insuranceCategory: 15,
    maintenanceAnnual: 600,
    tireLifeKm: 45000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 0,
    curbWeight: 1620,
    releaseYear: 2024,
  },
  {
    id: 'c4-essence',
    label: 'Citroën C4 PureTech 130',
    brand: 'Citroën',
    searchModel: 'C4',
    category: 'compact',
    energy: 'gasoline',
    purchasePrice: 28900,
    consumption: 5.9,
    co2: 133,
    insuranceCategory: 13,
    maintenanceAnnual: 440,
    tireLifeKm: 42000,
    tireSetPrice: 540,
    malus: 60,
    bonus: 0,
    curbWeight: 1273,
    releaseYear: 2024,
  },
  {
    id: 'ibiza-essence',
    label: 'Seat Ibiza 1.0 TSI 95',
    brand: 'Seat',
    searchModel: 'Ibiza',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 20900,
    consumption: 5.5,
    co2: 125,
    insuranceCategory: 11,
    maintenanceAnnual: 400,
    tireLifeKm: 42000,
    tireSetPrice: 500,
    malus: 0,
    bonus: 0,
    curbWeight: 1165,
    releaseYear: 2024,
  },
  {
    id: 'kamiq-essence',
    label: 'Skoda Kamiq 1.0 TSI 116',
    brand: 'Skoda',
    searchModel: 'Kamiq',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 27500,
    consumption: 5.8,
    co2: 132,
    insuranceCategory: 12,
    maintenanceAnnual: 440,
    tireLifeKm: 42000,
    tireSetPrice: 540,
    malus: 60,
    bonus: 0,
    curbWeight: 1239,
    releaseYear: 2024,
  },
  // --- Breaks & berlines familiales ---
  {
    id: '508-sw-hybrid',
    label: 'Peugeot 508 SW Hybrid 180 e-EAT8',
    brand: 'Peugeot',
    searchModel: '508 SW',
    category: 'estate',
    energy: 'phev',
    purchasePrice: 49900,
    consumption: 1.6,
    co2: 26,
    insuranceCategory: 16,
    maintenanceAnnual: 620,
    tireLifeKm: 42000,
    tireSetPrice: 720,
    malus: 0,
    bonus: 0,
    curbWeight: 1745,
    releaseYear: 2024,
    wltpRangeKm: 55,
  },
  {
    id: 'superb-combi-diesel',
    label: 'Skoda Superb Combi 2.0 TDI 150 DSG',
    brand: 'Skoda',
    searchModel: 'Superb Combi',
    category: 'estate',
    energy: 'diesel',
    purchasePrice: 43900,
    consumption: 5.1,
    co2: 134,
    insuranceCategory: 15,
    maintenanceAnnual: 660,
    tireLifeKm: 45000,
    tireSetPrice: 700,
    malus: 0,
    bonus: 0,
    curbWeight: 1612,
    releaseYear: 2024,
  },
  // --- EV élargi toutes gammes (2024-2026) ---
  {
    id: 'ec3-aircross-electric',
    label: 'Citroën ë-C3 Aircross 44kWh',
    brand: 'Citroën',
    searchModel: 'C3 Aircross',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 27400,
    consumption: 16.7,
    co2: 0,
    insuranceCategory: 12,
    maintenanceAnnual: 210,
    tireLifeKm: 38000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 4000,
    curbWeight: 1450,
    releaseYear: 2025,
    wltpRangeKm: 300,
  },
  {
    id: 'r4-etech-electric',
    label: 'Renault 4 E-Tech 150 52kWh',
    brand: 'Renault',
    searchModel: '4 E-Tech',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 30900,
    consumption: 15.5,
    co2: 0,
    insuranceCategory: 13,
    maintenanceAnnual: 210,
    tireLifeKm: 38000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 4000,
    curbWeight: 1462,
    releaseYear: 2025,
    wltpRangeKm: 400,
  },
  {
    id: 'mini-cooper-e',
    label: 'Mini Cooper E 184ch',
    brand: 'Mini',
    searchModel: 'Cooper',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 34900,
    consumption: 14.3,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 36000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 4000,
    curbWeight: 1605,
    releaseYear: 2024,
    wltpRangeKm: 305,
  },
  {
    id: 'cupra-born-electric',
    label: 'Cupra Born 59kWh 204ch',
    brand: 'Cupra',
    searchModel: 'Born',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 39990,
    consumption: 15.8,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 250,
    tireLifeKm: 36000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 4000,
    curbWeight: 1812,
    releaseYear: 2024,
    wltpRangeKm: 426,
  },
  {
    id: 'smart-hashtag1-electric',
    label: 'Smart #1 Pro+ 66kWh',
    brand: 'Smart',
    searchModel: '#1',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 38900,
    consumption: 16.8,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 36000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 4000,
    curbWeight: 1820,
    releaseYear: 2024,
    wltpRangeKm: 420,
  },
  {
    id: 'byd-dolphin-electric',
    label: 'BYD Dolphin Comfort 60kWh',
    brand: 'BYD',
    searchModel: 'Dolphin',
    category: 'compact',
    energy: 'electric',
    purchasePrice: 30990,
    consumption: 15.9,
    co2: 0,
    insuranceCategory: 13,
    maintenanceAnnual: 230,
    tireLifeKm: 38000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 4000,
    curbWeight: 1658,
    releaseYear: 2024,
    wltpRangeKm: 427,
  },
  {
    id: 'modely-perf-electric',
    label: 'Tesla Model Y Performance',
    brand: 'Tesla',
    searchModel: 'Model Y',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 59990,
    consumption: 17.5,
    co2: 0,
    insuranceCategory: 19,
    maintenanceAnnual: 300,
    tireLifeKm: 32000,
    tireSetPrice: 920,
    malus: 0,
    bonus: 0,
    curbWeight: 2003,
    releaseYear: 2024,
    wltpRangeKm: 514,
  },
  {
    id: 'volvo-ex30-electric',
    label: 'Volvo EX30 Single Motor Extended Range',
    brand: 'Volvo',
    searchModel: 'EX30',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 41500,
    consumption: 16.2,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 260,
    tireLifeKm: 36000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 4000,
    curbWeight: 1830,
    releaseYear: 2024,
    wltpRangeKm: 476,
  },
  {
    id: 'kia-niro-ev-electric',
    label: 'Kia Niro EV 64kWh',
    brand: 'Kia',
    searchModel: 'Niro EV',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 42990,
    consumption: 16.2,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 240,
    tireLifeKm: 38000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 4000,
    curbWeight: 1739,
    releaseYear: 2024,
    wltpRangeKm: 460,
  },
  {
    id: 'hyundai-inster-electric',
    label: 'Hyundai Inster Long Range 49kWh',
    brand: 'Hyundai',
    searchModel: 'Inster',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 25000,
    consumption: 15.0,
    co2: 0,
    insuranceCategory: 11,
    maintenanceAnnual: 200,
    tireLifeKm: 36000,
    tireSetPrice: 480,
    malus: 0,
    bonus: 4000,
    curbWeight: 1385,
    releaseYear: 2025,
    wltpRangeKm: 360,
  },
  {
    id: 'jeep-avenger-electric',
    label: 'Jeep Avenger électrique 156ch',
    brand: 'Jeep',
    searchModel: 'Avenger',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 35900,
    consumption: 15.4,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 220,
    tireLifeKm: 38000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1536,
    releaseYear: 2024,
    wltpRangeKm: 400,
  },
  // --- Batch enrichissement marché France 2023-2026 ---
  // Compactes diesel (→ bucket "Compacte diesel")
  {
    id: 'golf-diesel',
    label: 'Volkswagen Golf 2.0 TDI 150 DSG',
    brand: 'Volkswagen',
    searchModel: 'Golf',
    category: 'compact',
    energy: 'diesel',
    purchasePrice: 36900,
    consumption: 4.8,
    co2: 126,
    insuranceCategory: 14,
    maintenanceAnnual: 600,
    tireLifeKm: 45000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 0,
    curbWeight: 1390,
    releaseYear: 2024,
  },
  {
    id: 'focus-diesel',
    label: 'Ford Focus 1.5 EcoBlue 115 diesel',
    brand: 'Ford',
    searchModel: 'Focus',
    category: 'compact',
    energy: 'diesel',
    purchasePrice: 31900,
    consumption: 4.5,
    co2: 119,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 0,
    curbWeight: 1360,
    releaseYear: 2024,
  },
  {
    id: 'astra-diesel',
    label: 'Opel Astra 1.5 Diesel 130',
    brand: 'Opel',
    searchModel: 'Astra',
    category: 'compact',
    energy: 'diesel',
    purchasePrice: 33400,
    consumption: 4.6,
    co2: 121,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1370,
    releaseYear: 2024,
  },
  {
    id: 'leon-diesel',
    label: 'Seat Leon 2.0 TDI 150',
    brand: 'Seat',
    searchModel: 'Leon',
    category: 'compact',
    energy: 'diesel',
    purchasePrice: 34900,
    consumption: 4.7,
    co2: 123,
    insuranceCategory: 14,
    maintenanceAnnual: 580,
    tireLifeKm: 45000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1385,
    releaseYear: 2024,
  },
  // Compactes hybrides (renfort bucket "Compacte hybride")
  {
    id: 'civic-hybrid',
    label: 'Honda Civic e:HEV 184',
    brand: 'Honda',
    searchModel: 'Civic',
    category: 'compact',
    energy: 'hybrid',
    purchasePrice: 36900,
    consumption: 4.8,
    co2: 108,
    insuranceCategory: 14,
    maintenanceAnnual: 460,
    tireLifeKm: 42000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 0,
    curbWeight: 1487,
    releaseYear: 2024,
  },
  {
    id: 'swace-hybrid',
    label: 'Suzuki Swace Hybrid 140',
    brand: 'Suzuki',
    searchModel: 'Swace',
    category: 'compact',
    energy: 'hybrid',
    purchasePrice: 30900,
    consumption: 4.5,
    co2: 102,
    insuranceCategory: 13,
    maintenanceAnnual: 400,
    tireLifeKm: 45000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 0,
    curbWeight: 1375,
    releaseYear: 2024,
  },
  {
    id: 'ceed-hybrid',
    label: 'Kia Ceed 1.5 T-GDi mild hybrid 160',
    brand: 'Kia',
    searchModel: 'Ceed',
    category: 'compact',
    energy: 'hybrid',
    purchasePrice: 28900,
    consumption: 5.6,
    co2: 127,
    insuranceCategory: 13,
    maintenanceAnnual: 440,
    tireLifeKm: 42000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 0,
    curbWeight: 1320,
    releaseYear: 2024,
  },
  // Compactes hybrides rechargeables (→ nouveau bucket "Compacte hybride rechargeable")
  {
    id: 'golf-ehybrid-phev',
    label: 'Volkswagen Golf eHybrid 204 plug-in',
    brand: 'Volkswagen',
    searchModel: 'Golf',
    category: 'compact',
    energy: 'phev',
    purchasePrice: 42900,
    consumption: 1.0,
    co2: 22,
    insuranceCategory: 15,
    maintenanceAnnual: 540,
    tireLifeKm: 40000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 0,
    curbWeight: 1551,
    releaseYear: 2024,
    wltpRangeKm: 88,
  },
  {
    id: 'leon-ehybrid-phev',
    label: 'Cupra Leon e-Hybrid 204 plug-in',
    brand: 'Cupra',
    searchModel: 'Leon',
    category: 'compact',
    energy: 'phev',
    purchasePrice: 41900,
    consumption: 1.1,
    co2: 24,
    insuranceCategory: 15,
    maintenanceAnnual: 520,
    tireLifeKm: 40000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 0,
    curbWeight: 1564,
    releaseYear: 2024,
    wltpRangeKm: 85,
  },
  {
    id: '308-phev',
    label: 'Peugeot 308 Hybrid 180 plug-in e-EAT8',
    brand: 'Peugeot',
    searchModel: '308',
    category: 'compact',
    energy: 'phev',
    purchasePrice: 41500,
    consumption: 1.2,
    co2: 27,
    insuranceCategory: 14,
    maintenanceAnnual: 520,
    tireLifeKm: 40000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1612,
    releaseYear: 2024,
    wltpRangeKm: 60,
  },
  // Berlines essence (→ bucket "Berline essence")
  {
    id: '508-essence',
    label: 'Peugeot 508 PureTech 130',
    brand: 'Peugeot',
    searchModel: '508',
    category: 'sedan',
    energy: 'gasoline',
    purchasePrice: 39900,
    consumption: 6.3,
    co2: 142,
    insuranceCategory: 15,
    maintenanceAnnual: 520,
    tireLifeKm: 42000,
    tireSetPrice: 660,
    malus: 210,
    bonus: 0,
    curbWeight: 1465,
    releaseYear: 2024,
  },
  {
    id: 'superb-essence',
    label: 'Skoda Superb 1.5 TSI 150 DSG',
    brand: 'Skoda',
    searchModel: 'Superb',
    category: 'sedan',
    energy: 'gasoline',
    purchasePrice: 38900,
    consumption: 6.1,
    co2: 138,
    insuranceCategory: 15,
    maintenanceAnnual: 540,
    tireLifeKm: 42000,
    tireSetPrice: 640,
    malus: 170,
    bonus: 0,
    curbWeight: 1480,
    releaseYear: 2024,
  },
  {
    id: 'mazda6-essence',
    label: 'Mazda6 2.0 e-Skyactiv G 165',
    brand: 'Mazda',
    searchModel: 'Mazda6',
    category: 'sedan',
    energy: 'gasoline',
    purchasePrice: 37500,
    consumption: 6.5,
    co2: 147,
    insuranceCategory: 15,
    maintenanceAnnual: 520,
    tireLifeKm: 42000,
    tireSetPrice: 640,
    malus: 310,
    bonus: 0,
    curbWeight: 1480,
    releaseYear: 2023,
  },
  {
    id: 'corolla-sedan-essence',
    label: 'Toyota Corolla Sedan 1.8 132',
    brand: 'Toyota',
    searchModel: 'Corolla Sedan',
    category: 'sedan',
    energy: 'gasoline',
    purchasePrice: 30900,
    consumption: 6.0,
    co2: 136,
    insuranceCategory: 13,
    maintenanceAnnual: 460,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 170,
    bonus: 0,
    curbWeight: 1350,
    releaseYear: 2024,
  },
  // Berlines diesel (renfort bucket "Berline diesel")
  {
    id: '508-diesel',
    label: 'Peugeot 508 BlueHDi 130 diesel',
    brand: 'Peugeot',
    searchModel: '508',
    category: 'sedan',
    energy: 'diesel',
    purchasePrice: 42900,
    consumption: 4.9,
    co2: 129,
    insuranceCategory: 15,
    maintenanceAnnual: 600,
    tireLifeKm: 45000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 0,
    curbWeight: 1530,
    releaseYear: 2024,
  },
  {
    id: 'superb-diesel',
    label: 'Skoda Superb 2.0 TDI 150 DSG',
    brand: 'Skoda',
    searchModel: 'Superb',
    category: 'sedan',
    energy: 'diesel',
    purchasePrice: 41900,
    consumption: 4.8,
    co2: 127,
    insuranceCategory: 15,
    maintenanceAnnual: 620,
    tireLifeKm: 45000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 0,
    curbWeight: 1545,
    releaseYear: 2024,
  },
  // Berlines hybrides (→ nouveau bucket "Berline hybride")
  {
    id: 'corolla-sedan-hybrid',
    label: 'Toyota Corolla Sedan Hybride 140h',
    brand: 'Toyota',
    searchModel: 'Corolla Sedan',
    category: 'sedan',
    energy: 'hybrid',
    purchasePrice: 33900,
    consumption: 4.5,
    co2: 102,
    insuranceCategory: 14,
    maintenanceAnnual: 400,
    tireLifeKm: 45000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1390,
    releaseYear: 2024,
  },
  {
    id: 'ioniq-hybrid',
    label: 'Hyundai Ioniq Hybrid 141',
    brand: 'Hyundai',
    searchModel: 'Ioniq',
    category: 'sedan',
    energy: 'hybrid',
    purchasePrice: 32900,
    consumption: 4.4,
    co2: 100,
    insuranceCategory: 14,
    maintenanceAnnual: 420,
    tireLifeKm: 45000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1420,
    releaseYear: 2023,
  },
  {
    id: 'seal-dmi-hybrid',
    label: 'BYD Seal DM-i 1.5',
    brand: 'BYD',
    searchModel: 'Seal',
    category: 'sedan',
    energy: 'hybrid',
    purchasePrice: 35900,
    consumption: 4.8,
    co2: 108,
    insuranceCategory: 15,
    maintenanceAnnual: 440,
    tireLifeKm: 42000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 0,
    curbWeight: 1685,
    releaseYear: 2025,
  },
  // Breaks essence (renfort bucket "Break essence")
  {
    id: '308-sw-essence',
    label: 'Peugeot 308 SW PureTech 130',
    brand: 'Peugeot',
    searchModel: '308 SW',
    category: 'estate',
    energy: 'gasoline',
    purchasePrice: 32900,
    consumption: 6.1,
    co2: 138,
    insuranceCategory: 13,
    maintenanceAnnual: 480,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 170,
    bonus: 0,
    curbWeight: 1355,
    releaseYear: 2024,
  },
  {
    id: 'golf-sw-essence',
    label: 'Volkswagen Golf SW 1.5 eTSI 150',
    brand: 'Volkswagen',
    searchModel: 'Golf SW',
    category: 'estate',
    energy: 'gasoline',
    purchasePrice: 35500,
    consumption: 6.2,
    co2: 140,
    insuranceCategory: 14,
    maintenanceAnnual: 560,
    tireLifeKm: 42000,
    tireSetPrice: 620,
    malus: 210,
    bonus: 0,
    curbWeight: 1370,
    releaseYear: 2024,
  },
  {
    id: 'focus-sw-essence',
    label: 'Ford Focus SW 1.0 EcoBoost 125',
    brand: 'Ford',
    searchModel: 'Focus SW',
    category: 'estate',
    energy: 'gasoline',
    purchasePrice: 31500,
    consumption: 6.0,
    co2: 137,
    insuranceCategory: 13,
    maintenanceAnnual: 480,
    tireLifeKm: 42000,
    tireSetPrice: 560,
    malus: 170,
    bonus: 0,
    curbWeight: 1395,
    releaseYear: 2024,
  },
  // Breaks hybrides (→ nouveau bucket "Break hybride")
  {
    id: '308-sw-hybrid',
    label: 'Peugeot 308 SW Hybrid 136',
    brand: 'Peugeot',
    searchModel: '308 SW',
    category: 'estate',
    energy: 'hybrid',
    purchasePrice: 37900,
    consumption: 5.0,
    co2: 113,
    insuranceCategory: 14,
    maintenanceAnnual: 500,
    tireLifeKm: 40000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1440,
    releaseYear: 2024,
  },
  {
    id: 'corolla-ts-hybrid',
    label: 'Toyota Corolla Touring Sports Hybride 140h',
    brand: 'Toyota',
    searchModel: 'Corolla Touring Sports',
    category: 'estate',
    energy: 'hybrid',
    purchasePrice: 34900,
    consumption: 4.6,
    co2: 104,
    insuranceCategory: 14,
    maintenanceAnnual: 400,
    tireLifeKm: 45000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1420,
    releaseYear: 2024,
  },
  {
    id: 'megane-estate-hybrid',
    label: 'Renault Mégane Estate E-Tech full hybrid 145',
    brand: 'Renault',
    searchModel: 'Mégane Estate',
    category: 'estate',
    energy: 'hybrid',
    purchasePrice: 33500,
    consumption: 4.7,
    co2: 106,
    insuranceCategory: 13,
    maintenanceAnnual: 440,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1430,
    releaseYear: 2024,
  },
  // SUV diesel (→ bucket "SUV diesel")
  {
    id: 'tiguan-diesel',
    label: 'Volkswagen Tiguan 2.0 TDI 150 DSG',
    brand: 'Volkswagen',
    searchModel: 'Tiguan',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 44900,
    consumption: 5.4,
    co2: 142,
    insuranceCategory: 16,
    maintenanceAnnual: 640,
    tireLifeKm: 45000,
    tireSetPrice: 740,
    malus: 0,
    bonus: 0,
    curbWeight: 1660,
    releaseYear: 2024,
  },
  {
    id: 'duster-diesel',
    label: 'Dacia Duster Blue dCi 115',
    brand: 'Dacia',
    searchModel: 'Duster',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 26500,
    consumption: 4.9,
    co2: 129,
    insuranceCategory: 12,
    maintenanceAnnual: 480,
    tireLifeKm: 45000,
    tireSetPrice: 560,
    malus: 0,
    bonus: 0,
    curbWeight: 1410,
    releaseYear: 2024,
  },
  {
    id: 'tucson-diesel',
    label: 'Hyundai Tucson 1.6 CRDi 136 diesel',
    brand: 'Hyundai',
    searchModel: 'Tucson',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 38900,
    consumption: 5.3,
    co2: 139,
    insuranceCategory: 15,
    maintenanceAnnual: 600,
    tireLifeKm: 45000,
    tireSetPrice: 680,
    malus: 0,
    bonus: 0,
    curbWeight: 1610,
    releaseYear: 2024,
  },
  {
    id: 'sportage-diesel',
    label: 'Kia Sportage 1.6 CRDi 136 diesel',
    brand: 'Kia',
    searchModel: 'Sportage',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 39500,
    consumption: 5.3,
    co2: 139,
    insuranceCategory: 15,
    maintenanceAnnual: 600,
    tireLifeKm: 45000,
    tireSetPrice: 680,
    malus: 0,
    bonus: 0,
    curbWeight: 1620,
    releaseYear: 2024,
  },
  {
    id: 'qashqai-diesel',
    label: 'Nissan Qashqai 1.5 dCi 115 diesel',
    brand: 'Nissan',
    searchModel: 'Qashqai',
    category: 'suv',
    energy: 'diesel',
    purchasePrice: 36900,
    consumption: 5.2,
    co2: 137,
    insuranceCategory: 15,
    maintenanceAnnual: 580,
    tireLifeKm: 45000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 0,
    curbWeight: 1505,
    releaseYear: 2024,
  },
  // Utilitaires familiaux diesel (→ bucket "Utilitaire familial diesel")
  {
    id: 'berlingo-diesel',
    label: 'Citroën Berlingo BlueHDi 130 diesel',
    brand: 'Citroën',
    searchModel: 'Berlingo',
    category: 'utility',
    energy: 'diesel',
    purchasePrice: 32500,
    consumption: 5.3,
    co2: 139,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1490,
    releaseYear: 2024,
  },
  {
    id: 'rifter-diesel',
    label: 'Peugeot Rifter BlueHDi 130 diesel',
    brand: 'Peugeot',
    searchModel: 'Rifter',
    category: 'utility',
    energy: 'diesel',
    purchasePrice: 32900,
    consumption: 5.3,
    co2: 139,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1495,
    releaseYear: 2024,
  },
  {
    id: 'kangoo-diesel',
    label: 'Renault Kangoo Blue dCi 115 diesel',
    brand: 'Renault',
    searchModel: 'Kangoo',
    category: 'utility',
    energy: 'diesel',
    purchasePrice: 31900,
    consumption: 5.4,
    co2: 142,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1520,
    releaseYear: 2024,
  },
  {
    id: 'caddy-diesel',
    label: 'Volkswagen Caddy 2.0 TDI 122 diesel',
    brand: 'Volkswagen',
    searchModel: 'Caddy',
    category: 'utility',
    energy: 'diesel',
    purchasePrice: 36900,
    consumption: 5.5,
    co2: 144,
    insuranceCategory: 14,
    maintenanceAnnual: 600,
    tireLifeKm: 45000,
    tireSetPrice: 620,
    malus: 0,
    bonus: 0,
    curbWeight: 1605,
    releaseYear: 2024,
  },
  {
    id: 'combo-diesel',
    label: 'Opel Combo Life BlueHDi 130 diesel',
    brand: 'Opel',
    searchModel: 'Combo Life',
    category: 'utility',
    energy: 'diesel',
    purchasePrice: 32200,
    consumption: 5.3,
    co2: 139,
    insuranceCategory: 13,
    maintenanceAnnual: 560,
    tireLifeKm: 45000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1485,
    releaseYear: 2024,
  },
  // Utilitaires familiaux électriques (→ nouveau bucket "Utilitaire familial électrique")
  {
    id: 'erifter-electric',
    label: 'Peugeot e-Rifter électrique 136ch',
    brand: 'Peugeot',
    searchModel: 'Rifter',
    category: 'utility',
    energy: 'electric',
    purchasePrice: 40900,
    consumption: 19.9,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1760,
    releaseYear: 2024,
    wltpRangeKm: 280,
  },
  {
    id: 'kangoo-etech-electric',
    label: 'Renault Kangoo E-Tech électrique 90kW',
    brand: 'Renault',
    searchModel: 'Kangoo',
    category: 'utility',
    energy: 'electric',
    purchasePrice: 39900,
    consumption: 20.2,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1776,
    releaseYear: 2024,
    wltpRangeKm: 285,
  },
  {
    id: 'comboe-electric',
    label: 'Opel Combo-e Life électrique 136ch',
    brand: 'Opel',
    searchModel: 'Combo Life',
    category: 'utility',
    energy: 'electric',
    purchasePrice: 40500,
    consumption: 19.8,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 240,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1755,
    releaseYear: 2024,
    wltpRangeKm: 280,
  },
  {
    id: 'tourneo-connect-electric',
    label: 'Ford E-Tourneo Connect électrique',
    brand: 'Ford',
    searchModel: 'Tourneo Connect',
    category: 'utility',
    energy: 'electric',
    purchasePrice: 43900,
    consumption: 19.5,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 250,
    tireLifeKm: 42000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 4000,
    curbWeight: 1820,
    releaseYear: 2024,
    wltpRangeKm: 300,
  },
  // --- Enrichissement général : citadines, compactes, SUV (essence/hybride/EV) ---
  {
    id: 'corsa-essence',
    label: 'Opel Corsa 1.2 Turbo 100',
    brand: 'Opel',
    searchModel: 'Corsa',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 20900,
    consumption: 5.5,
    co2: 124,
    insuranceCategory: 11,
    maintenanceAnnual: 380,
    tireLifeKm: 40000,
    tireSetPrice: 480,
    malus: 0,
    bonus: 0,
    curbWeight: 1165,
    releaseYear: 2024,
  },
  {
    id: 'aygox-essence',
    label: 'Toyota Aygo X 1.0 72',
    brand: 'Toyota',
    searchModel: 'Aygo X',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 17500,
    consumption: 4.9,
    co2: 111,
    insuranceCategory: 10,
    maintenanceAnnual: 320,
    tireLifeKm: 42000,
    tireSetPrice: 420,
    malus: 0,
    bonus: 0,
    curbWeight: 945,
    releaseYear: 2024,
  },
  {
    id: 'i10-essence',
    label: 'Hyundai i10 1.0 67',
    brand: 'Hyundai',
    searchModel: 'i10',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 16900,
    consumption: 5.2,
    co2: 118,
    insuranceCategory: 10,
    maintenanceAnnual: 320,
    tireLifeKm: 42000,
    tireSetPrice: 400,
    malus: 0,
    bonus: 0,
    curbWeight: 1000,
    releaseYear: 2024,
  },
  {
    id: 'picanto-essence',
    label: 'Kia Picanto 1.0 63',
    brand: 'Kia',
    searchModel: 'Picanto',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 16500,
    consumption: 5.3,
    co2: 120,
    insuranceCategory: 10,
    maintenanceAnnual: 320,
    tireLifeKm: 42000,
    tireSetPrice: 400,
    malus: 0,
    bonus: 0,
    curbWeight: 1010,
    releaseYear: 2024,
  },
  {
    id: 'i20-essence',
    label: 'Hyundai i20 1.0 T-GDi 100',
    brand: 'Hyundai',
    searchModel: 'i20',
    category: 'cityCar',
    energy: 'gasoline',
    purchasePrice: 21500,
    consumption: 5.4,
    co2: 122,
    insuranceCategory: 11,
    maintenanceAnnual: 380,
    tireLifeKm: 42000,
    tireSetPrice: 480,
    malus: 0,
    bonus: 0,
    curbWeight: 1135,
    releaseYear: 2024,
  },
  {
    id: 'swift-hybrid',
    label: 'Suzuki Swift 1.2 Hybrid 83',
    brand: 'Suzuki',
    searchModel: 'Swift',
    category: 'cityCar',
    energy: 'hybrid',
    purchasePrice: 19900,
    consumption: 4.4,
    co2: 99,
    insuranceCategory: 11,
    maintenanceAnnual: 340,
    tireLifeKm: 42000,
    tireSetPrice: 460,
    malus: 0,
    bonus: 0,
    curbWeight: 949,
    releaseYear: 2024,
  },
  {
    id: 'mokka-essence',
    label: 'Opel Mokka 1.2 Turbo 130',
    brand: 'Opel',
    searchModel: 'Mokka',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 28900,
    consumption: 6.0,
    co2: 136,
    insuranceCategory: 13,
    maintenanceAnnual: 450,
    tireLifeKm: 40000,
    tireSetPrice: 560,
    malus: 170,
    bonus: 0,
    curbWeight: 1280,
    releaseYear: 2024,
  },
  {
    id: 'juke-essence',
    label: 'Nissan Juke DIG-T 114',
    brand: 'Nissan',
    searchModel: 'Juke',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 26900,
    consumption: 6.1,
    co2: 138,
    insuranceCategory: 13,
    maintenanceAnnual: 440,
    tireLifeKm: 40000,
    tireSetPrice: 560,
    malus: 170,
    bonus: 0,
    curbWeight: 1262,
    releaseYear: 2024,
  },
  {
    id: 'puma-essence',
    label: 'Ford Puma 1.0 EcoBoost mHEV 125',
    brand: 'Ford',
    searchModel: 'Puma',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 27500,
    consumption: 5.9,
    co2: 133,
    insuranceCategory: 13,
    maintenanceAnnual: 440,
    tireLifeKm: 40000,
    tireSetPrice: 560,
    malus: 60,
    bonus: 0,
    curbWeight: 1280,
    releaseYear: 2024,
  },
  {
    id: 'niro-hybrid',
    label: 'Kia Niro Hybrid 141',
    brand: 'Kia',
    searchModel: 'Niro',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 33900,
    consumption: 4.7,
    co2: 105,
    insuranceCategory: 14,
    maintenanceAnnual: 420,
    tireLifeKm: 42000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1475,
    releaseYear: 2024,
  },
  {
    id: 'symbioz-hybrid',
    label: 'Renault Symbioz E-Tech full hybrid 145',
    brand: 'Renault',
    searchModel: 'Symbioz',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 33500,
    consumption: 4.6,
    co2: 104,
    insuranceCategory: 14,
    maintenanceAnnual: 420,
    tireLifeKm: 42000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 0,
    curbWeight: 1480,
    releaseYear: 2025,
  },
  {
    id: 'frontera-hybrid',
    label: 'Opel Frontera Hybrid 136',
    brand: 'Opel',
    searchModel: 'Frontera',
    category: 'suv',
    energy: 'hybrid',
    purchasePrice: 28900,
    consumption: 5.4,
    co2: 123,
    insuranceCategory: 13,
    maintenanceAnnual: 420,
    tireLifeKm: 42000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 0,
    curbWeight: 1295,
    releaseYear: 2025,
  },
  {
    id: 'kia-ev3-electric',
    label: 'Kia EV3 Long Range 81kWh',
    brand: 'Kia',
    searchModel: 'EV3',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 42990,
    consumption: 15.8,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 240,
    tireLifeKm: 38000,
    tireSetPrice: 640,
    malus: 0,
    bonus: 4000,
    curbWeight: 1885,
    releaseYear: 2025,
    wltpRangeKm: 605,
  },
  {
    id: 'elroq-electric',
    label: 'Skoda Elroq 85',
    brand: 'Skoda',
    searchModel: 'Elroq',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 43900,
    consumption: 16.4,
    co2: 0,
    insuranceCategory: 15,
    maintenanceAnnual: 260,
    tireLifeKm: 38000,
    tireSetPrice: 660,
    malus: 0,
    bonus: 4000,
    curbWeight: 1955,
    releaseYear: 2025,
    wltpRangeKm: 560,
  },
  {
    id: 'leapmotor-b10-electric',
    label: 'Leapmotor B10 67kWh',
    brand: 'Leapmotor',
    searchModel: 'B10',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 32900,
    consumption: 16.5,
    co2: 0,
    insuranceCategory: 13,
    maintenanceAnnual: 230,
    tireLifeKm: 38000,
    tireSetPrice: 600,
    malus: 0,
    bonus: 4000,
    curbWeight: 1755,
    releaseYear: 2025,
    wltpRangeKm: 430,
  },
  {
    id: 'tucson-essence',
    label: 'Hyundai Tucson 1.6 T-GDi 150',
    brand: 'Hyundai',
    searchModel: 'Tucson',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 34900,
    consumption: 6.7,
    co2: 152,
    insuranceCategory: 14,
    maintenanceAnnual: 480,
    tireLifeKm: 42000,
    tireSetPrice: 660,
    malus: 540,
    bonus: 0,
    curbWeight: 1480,
    releaseYear: 2024,
  },
  {
    id: 'sportage-essence',
    label: 'Kia Sportage 1.6 T-GDi 150',
    brand: 'Kia',
    searchModel: 'Sportage',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 35500,
    consumption: 6.7,
    co2: 152,
    insuranceCategory: 14,
    maintenanceAnnual: 480,
    tireLifeKm: 42000,
    tireSetPrice: 660,
    malus: 540,
    bonus: 0,
    curbWeight: 1490,
    releaseYear: 2024,
  },
  {
    id: 'i20-electric-corsa',
    label: 'Opel Corsa Electric 50kWh',
    brand: 'Opel',
    searchModel: 'Corsa',
    category: 'cityCar',
    energy: 'electric',
    purchasePrice: 34900,
    consumption: 15.2,
    co2: 0,
    insuranceCategory: 12,
    maintenanceAnnual: 200,
    tireLifeKm: 38000,
    tireSetPrice: 520,
    malus: 0,
    bonus: 4000,
    curbWeight: 1530,
    releaseYear: 2024,
    wltpRangeKm: 357,
  },
  {
    id: 'mokka-electric',
    label: 'Opel Mokka Electric 54kWh',
    brand: 'Opel',
    searchModel: 'Mokka',
    category: 'suv',
    energy: 'electric',
    purchasePrice: 38900,
    consumption: 16.3,
    co2: 0,
    insuranceCategory: 14,
    maintenanceAnnual: 220,
    tireLifeKm: 38000,
    tireSetPrice: 580,
    malus: 0,
    bonus: 4000,
    curbWeight: 1598,
    releaseYear: 2024,
    wltpRangeKm: 406,
  },
  {
    id: 'aygox-essence-c3-aircross',
    label: 'Citroën C3 Aircross PureTech 100',
    brand: 'Citroën',
    searchModel: 'C3 Aircross',
    category: 'suv',
    energy: 'gasoline',
    purchasePrice: 21900,
    consumption: 5.9,
    co2: 133,
    insuranceCategory: 12,
    maintenanceAnnual: 400,
    tireLifeKm: 42000,
    tireSetPrice: 520,
    malus: 60,
    bonus: 0,
    curbWeight: 1283,
    releaseYear: 2024,
  },
] as const
